# -*- coding: utf-8 -*-
"""youtube_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11f-BPSNzna_Mzx8xZEa2zyDYJuFTyWEI
"""

import os
os.environ["GEMINI_API_KEY"] = os.getenv("GEMINI_API_KEY", "your_gemini_api_key_here")

"""Install Libraries and youtube API for loading transcript

There are a lot of version mismatches so first update the langchain then install gemini and import
"""

!pip install --upgrade langchain langchain-core langchain-community langchain-google-genai

!pip install -q youtube-transcript-api langchain-community faiss-cpu tiktoken python-dotenv

#For using gemini
!pip install -q langchain-google-genai

"""The new langchain doesnt have langchain.text splitter instead
from langchain_text_splitters import RecursiveCharacterTextSplitter0
"""

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
#YouTubeTranscriptApi -   Used to fetch sutitles , TranscriptDisabled- The safety net , sometimes creators dont have subtitles so this prevents fetch error
from langchain_text_splitters import RecursiveCharacterTextSplitter
#For gogle use google generative AI
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

"""Step 1a- Indexing (Document Ingestion)"""

video_id="Gfr50f6ZBvo" # Only the id and not full URL

try:
  # If we dont care which language, this returns the "best" one
  # 1 step is to laod the transcript for the particular video
  # get_transcript is replaced by fetch and .to_raw_data and YouTubeTranscriptApi()
  transcript_list= YouTubeTranscriptApi().fetch(video_id, languages=["en"]).to_raw_data()
  # This will return the text as well as the timestamps in the form of list and we only need text so take all the text and join them using " "
  transcript=" ".join(chunk['text'] for chunk in transcript_list)
  print(transcript)

except TranscriptsDisabled:
  print("No caption available for this video.")

"""Step 1b - Indexing(Text Splitting)"""

# We have to divide this big transcript into meaningful chunks - splitting and create documents of it
splitter= RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks=splitter.create_documents([transcript])

len(chunks)

chunks[0]

"""Step 1c and 1d - Indexing(Embedding Generation and Storing in Vector Store)"""

import time
# For all documents we have to create embeddings and store them in vector stores for retrival

# (Setting task_type to 'retrieval_document' mathematically optimizes the vector layout for our chunks)
embeddings= GoogleGenerativeAIEmbeddings(model="gemini-embedding-2",
    task_type="retrieval_document")
vector_store= FAISS.from_documents([chunks[0]],embeddings) # chunks[0] is tuple and we can only pass dict so [chunks[0]]

# Free tier wont allow to make more than 100 embedding calls so you have to divide everything in batch
batch_size= 5

print(f"Embedding {len(chunks)} chunks safely in batches...")

for i in range(1, len(chunks), batch_size):
    batch = chunks[i : i + batch_size]

    # Push a tiny batch of text
    vector_store.add_documents(batch)
    print(f"Successfully processed chunks {i} to {i + len(batch)}")

    # Pause for 3-5 seconds to clear the 100 requests/minute tier filter
    time.sleep(3)

print("FAISS Database successfully built.")

# Now we can see the id's
vector_store.index_to_docstore_id

# See any document byb its id
vector_store.get_by_ids(['db289535-1db8-4be5-a913-a46e863d8d66'])

"""###Step 2 - Retieval"""

retriever= vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 4})
retriever

# Since retriever is a runnable we can call invoke
retriever.invoke("What is deepmind")

"""### Step 3 - Augmentation (Using relevant document and Query to make a prompt and send it to LLM"""

# chat-bison 3 is completely shut down
llm= ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2)

prompt= PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient , just say that you don't know.

      {context}
      Question: {question}
    """,
    input_variables=["context", "question"]
)

question= "Is the topic of aliens discused in this video? If yes then what was discussed."
retrieved_docs= retriever.invoke(question)

retrieved_docs

# We can't send everything so we will only take the text and then pass it
context_text="\n\n".join(doc.page_content for doc in retrieved_docs)

final_prompt=prompt.invoke({"context": context_text, "question": question})

"""### Step 4- Genaration"""

answer=llm.invoke(final_prompt)
print(answer.content)

"""### Building a chain"""

from langchain_core.runnables import RunnableParallel , RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_docs):
  context_text="\n\n".join(doc.page_content for doc in retrieved_docs)
  return context_text

parallel_chain= RunnableParallel({
    'context': retriever | RunnableLambda(format_docs),
    'question': RunnablePassthrough()
})

parallel_chain.invoke("Who is Demis")

# Make a parser as we need output ion string format
parser= StrOutputParser()

# We have made our parallel chain, now we need our serial chain and connect it with our parallel chain
main_chain= parallel_chain | prompt | llm | parser

main_chain.invoke("Can you summarise the video")

